export default {
	languageOptions: {
		ecmaVersion: 'latest',
		sourceType: 'module'
	},
	rules: {
		'accessor-pairs': 'error',
		'block-scoped-var': 'error',
		camelcase: 'error',
		complexity: ['error', 20],
		'default-case': 'error',
		'dot-notation': 'error',
		eqeqeq: ['off', 'smart'],
		'max-lines': ['error', { max: 300, skipComments: true, skipBlankLines: true }],
		'max-nested-callbacks': ['error', { max: 3 }],
		'new-cap': 'error',
		'no-alert': 'error',
		'no-array-constructor': 'error',
		'no-bitwise': 'error',
		'no-caller': 'error',
		'no-cond-assign': 'error',
		'no-constant-condition': 'error',
		'no-control-regex': 'error',
		'no-debugger': 'warn',
		'no-delete-var': 'error',
		'no-div-regex': 'error',
		'no-dupe-args': 'error',
		'no-dupe-keys': 'error',
		'no-duplicate-case': 'error',
		'no-empty': 'error',
		'no-empty-character-class': 'error',
		'no-eval': 'error',
		'no-ex-assign': 'error',
		'no-extend-native': 'error',
		'no-extra-bind': 'error',
		'no-extra-boolean-cast': 'error',
		'no-fallthrough': 'error',
		'no-func-assign': 'error',
		'no-implied-eval': 'error',
		'no-invalid-regexp': 'error',
		'no-irregular-whitespace': 'error',
		'no-iterator': 'error',
		'no-label-var': 'error',
		'no-labels': 'error',
		'no-multi-str': 'error',
		'no-nested-ternary': 'error',
		'no-new': 'error',
		'no-new-func': 'error',
		'no-new-wrappers': 'error',
		'no-octal': 'error',
		'no-octal-escape': 'error',
		'no-proto': 'error',
		'no-redeclare': 'error',
		'no-return-assign': 'error',
		'no-self-compare': 'error',
		'no-sequences': 'error',
		'no-shadow': 'error',
		'no-shadow-restricted-names': 'error',
		'no-sparse-arrays': 'error',
		'no-throw-literal': 'error',
		'no-undef': 'error',
		'no-unexpected-multiline': 'error',
		'no-unneeded-ternary': 'error',
		'no-unreachable': 'error',
		'no-unused-vars': 'error',
		'no-use-before-define': 'error',
		'no-useless-call': 'error',
		'no-void': 'error',
		'no-warning-comments': 'warn',
		'operator-assignment': 'error',
		'use-isnan': 'error',
		'valid-typeof': 'error',
		yoda: ['error', 'never']
	}
};
